# Reinforcement Learning settings
LEARNING_RATE = 0.0001
DISCOUNT_FACTOR = 0.75

ACTION_POSSIBILITIES = 12
STATE_SIZE = 4 + 3 + (ACTION_POSSIBILITIES*3)

BATCH_SIZE = 250

BUFFER_MAX_LEN = 100000

# Directorioes
MODELS_PATH = "../data/models"
TENSORFLOW_LOG_PATH = "../data/tensorflow"
