# Reinforcement Learning settings
LEARNING_RATE = 0.001
DISCOUNT_FACTOR = 0.8

ACTION_POSSIBILITIES = 12
STATE_SIZE = 4 + 4 + (ACTION_POSSIBILITIES*3)

BATCH_SIZE = 400

BUFFER_MAX_LEN = 100000

# Directorioes
MODELS_PATH = "../data/models"
TENSORFLOW_LOG_PATH = "../data/tensorflow"
