# Reinforcement Learning settings
LEARNING_RATE = 0.0001
DISCOUNT_FACTOR = 0.75

STATE_SIZE = 4 + 3 + 8 + 8 + 8
ACTION_POSSIBILITIES = 8
BATCH_SIZE = 150

BUFFER_MAX_LEN = 60000

EPSILON = 1.0
EPSILON_DECAY = 0.9993
MIN_EPSILON = EPSILON - EPSILON_DECAY

# Directorioes
MODELS_PATH = "../data/models"
TENSORFLOW_LOG_PATH = "../data/tensorflow"
